databases:
  - name: dib-db
    plan: free
    databaseName: dib
    user: dib

services:
  - type: web
    name: dating-itinerary-builder-backend
    env: docker
    plan: free
    branch: main
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dib-db
          property: connectionString
      - key: CORS_ORIGINS
        value: "*"
